services:
  dev-host:
    image: local-dev-host:latest
    build:
      context: .
      dockerfile: Dockerfile.host
    command: sh -c "touch .pid && tail -f .pid"
    ports:
      - 1080:1080

  mock-server:
    image: mockserver/mockserver:5.14.0
    network_mode: "service:dev-host"
    volumes:
      - ./config:/config
    environment:
      - MOCKSERVER_INITIALIZATION_JSON_PATH=/config/initializer.json
      - MOCKSERVER_WATCH_INITIALIZATION_JSON=true
    depends_on:
      - dev-host
